### ISSUE TITLE
[Feature Request] Install tracker functionality

### ISSUE THREAD

**Issue by benswolo** [Klocman/Bulk-Crap-Uninstaller#537] opened 2023-09-17 00:04 UTC
There appears to be no way for the BCUninstaller to track an install. IObit uninstaller has a feature when you can install a .exe through the program by dragging and dropping it on the IOBit window, which will then track the install as well as everything that has changed in the system before and after. This makes it guaranteed that IOBit will remove everything that was installed for the program in question. 

There have been times when I tried uninstalling trial versions of software with BCU, but reinstalling it resulted in the same Trial Expiration behavior, even with the Low Certainty Registry edit modifier. This implies that there is residue that BCUninstaller is not picking up.

**Comment by Klocman** [comment] 2023-09-27 19:42
Duplicate of #258

**Closed by Klocman** 2023-09-27 19:42 UTC
