### ISSUE TITLE
'Unexpected Error' on startup

### ISSUE THREAD

**Issue by mvicari** [Klocman/Bulk-Crap-Uninstaller#500] opened 2023-06-08 14:10 UTC
```
System.Text.Json.JsonException
'I' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonTypeInfo`1 jsonTypeInfo)
   at UninstallTools.Factory.ScoopFactory.GetUninstallerEntries(ListGenerationCallback progressCallback)
   at UninstallTools.Factory.ApplicationUninstallerFactory.GetMiscUninstallerEntries(ListGenerationCallback progressCallback)

Inner: 
System.Text.Json.JsonReaderException
'I' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
```
```
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'main' bucket:
4c56a1c24 (HEAD -> master, origin/master, origin/HEAD) vcluster: Update to version 0.15.1
```

App seems to otherwise function fine after clicking through the error popups.

[This actually seems to be a duplicate of [issue 498](https://github.com/Klocman/Bulk-Crap-Uninstaller/issues/498).]

**Comment by Klocman** [comment] 2023-06-14 10:31
Duplicate of #498

**Closed by Klocman** 2023-06-14 10:31 UTC
