### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by canonrebel04** [Klocman/Bulk-Crap-Uninstaller#327] opened 2021-11-06 06:22 UTC
The feature request that I am putting in is a dark mode setting for the app. This might be hard to implement so I'm not expecting to get a response but its just an idea.

**Comment by Soumyadeep98O** [comment] 2021-11-30 13:11
https://github.com/Klocman/Bulk-Crap-Uninstaller/issues/228#issuecomment-453836494

**Comment by Klocman** [comment] 2022-02-06 17:07
Closing as duplicate of #228

**Closed by Klocman** 2022-02-06 17:07 UTC
Labels: duplicate
