### ISSUE TITLE
Google Earth Pro undetected leftovers

### ISSUE THREAD

**Issue by DmitriyYukhanov** [Klocman/Bulk-Crap-Uninstaller#85] opened 2017-07-27 22:31 UTC
I've uninstalled Google Earth Pro and noticed such leftovers were not detected:

**Files**

C:\WINDOWS\Installer\{09A8EA8A-9C9D-45E4-B20C-3F13C2CCD32C} folder with MainIcon.ico file:
![image](https://user-images.githubusercontent.com/883587/28694063-60cb0650-7330-11e7-8d00-1f4d8c14f30d.png)

C:\Users\focus\AppData\LocalLow\Google\GoogleEarth folder.
Worth noting, C:\Users\focus\AppData\LocalLow\Google\ was found as a bad confidence leftover. It could be suggested as a good confidence since there is only Google Earth related folder inside.

**Registry**

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.kml
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.kmz
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\AppID\{46A99B9C-4AC8-4EE9-AF7D-D02816CEC314}
(Default) - "GoogleEarth"

HKEY_CLASSES_ROOT\AppID\{7E7898C9-8E34-4314-9670-771BC5343D0E}
(Default) - "Keyhole"

This Keyhole app is related to the Google Earth:
HKEY_CLASSES_ROOT\Wow6432Node\CLSID\{63E6BE14-A742-4EEA-8AF3-0EC39F10F850}
AppID = {7E7898C9-8E34-4314-9670-771BC5343D0E}
HKEY_CLASSES_ROOT\Wow6432Node\CLSID\{63E6BE14-A742-4EEA-8AF3-0EC39F10F850}\LocalServer32
(Default) = C:\Program Files (x86)\Google\Google Earth Pro\client\googleearth.exe

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\AppID\googleearth.exe
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\AppID\Keyhole.EXE
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\GoogleEarth.AnimationControllerGE
and all other
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\GoogleEarth.*
![image](https://user-images.githubusercontent.com/883587/28694349-b5a1273a-7331-11e7-9bd6-79ece37f3c3d.png)

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Features\A8AE8A90D9C94E542BC0F3312CCC3DC2
It'a a same key as
HKEY_CLASSES_ROOT\Installer\Products\A8AE8A90D9C94E542BC0F3312CCC3DC2
Which has ProductName = Google Earth Pro

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Installer\UserData\S-1-5-18\Products\A8AE8A90D9C94E542BC0F3312CCC3DC2 (same A8AE8A90D9C94E542BC0F3312CCC3DC2 here)

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\UpgradeCodes\BEB4BB7555EFDAF4892EC1C6370B0D45
and
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Installer\UpgradeCodes\BEB4BB7555EFDAF4892EC1C6370B0D45
Since it has only one value named A8AE8A90D9C94E542BC0F3312CCC3DC2 inside.

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Keyhole.KHFeature
and all other
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Keyhole.KH*

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{3476FAB2-687F-4EA6-9AC2-88D72DC7D7FC}
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{3476FAB2-687F-4EA6-9AC2-88D72DC7D7FC}\1.0
(Default) - Google Earth 1.0 Type Library
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{3476FAB2-687F-4EA6-9AC2-88D72DC7D7FC}\1.0\0\win32
(Default) - C:\Program Files (x86)\Google\Google Earth Pro\client\googleearth.exe

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{1796A329-04C1-4C07-B28E-E4A807935C06}
(Default) - PointOnTerrainGE Class
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{1796A329-04C1-4C07-B28E-E4A807935C06}\LocalServer32 
(Default) - C:\Program Files (x86)\Google\Google Earth Pro\client\googleearth.exe

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{1A239250-B650-4B63-B4CF-7FCC4DC07DC6}
Same as previous, comes from HKEY_LOCAL_MACHINE\SOFTWARE\Classes\GoogleEarth.*

And all similar items at HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\ which linked from HKEY_LOCAL_MACHINE\SOFTWARE\Classes\GoogleEarth.*

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\Interface\{07F46615-1857-40CF-9AA9-872C9858E769}
and all other interfaces which has \ProxyStubClsid32 with default value {F4F7B301-7C59-4851-BA97-C51F110B590F} which corresponds to 
HKEY_CLASSES_ROOT\Wow6432Node\Interface\{F4F7B301-7C59-4851-BA97-C51F110B590F}
and
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Classes\Interface\{F4F7B301-7C59-4851-BA97-C51F110B590F}
And has default value IPointOnTerrainGE.
Not sure how to go to the IPointOnTerrainGE, from what point. But it's obvious it is belongs to the Google Earth.
Maybe last write time? Not sure.

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Installer\UserData\S-1-5-18\Components\01850E5281A52695DA5D0032120B6A3D
And all other components which has value name inside:
A8AE8A90D9C94E542BC0F3312CCC3DC2 (same as HKEY_CLASSES_ROOT\Installer\Products\A8AE8A90D9C94E542BC0F3312CCC3DC2)
There are lots of them left.

HKEY_USERS\.DEFAULT\Software\Google\Google Earth Pro
HKEY_USERS\S-1-5-21-1278579218-726299998-186589410-1001\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.kml
HKEY_USERS\S-1-5-21-1278579218-726299998-186589410-1001\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.kmz

**Comment by Klocman** [comment] 2017-07-29 21:42
Wow, this is a lot of undetected junk for a single application! Thank you for taking the time to write it all down, I'll add detection for these bit by bit.

At the moment BCU is not scanning HKEY_USERS by design to be on the safe side (in case other users want to keep the settings or need the "junk" for something that you don't know about).

HKEY_CLASSES_ROOT is the same as HKEY_LOCAL_MACHINE\SOFTWARE\Classes (they point to the same registry key), so they can be used interchangeably. Class cleanup is not really implemented at the moment since it needs to be very safe, it's best to use something like CCleaner afterwards for now.

**Comment by DmitriyYukhanov** [comment] 2017-07-29 21:46
Thanks for your quick reaction and additional details in your comment.
It would be nice to let BCU "I'm alone using this PC, feel free to touch HKEY_USERS!".
Regarding class cleanup - thanks for letting me know, will use CCleaner for that, though would be great to have it in BCU in future.

**Comment by Klocman** [comment] 2017-10-29 12:37
I split stuff related to classes to #138, it will have to wait. The rest of the junk seems to be detected now, so I'm closing the issue.

**Closed by Klocman** 2017-10-29 12:37 UTC
Labels: junk/app detection
