### ISSUE TITLE
Feature Request "Clear Leftover Files"

### ISSUE THREAD

**Issue by KDropZ** [Klocman/Bulk-Crap-Uninstaller#479] opened 2023-03-29 15:50 UTC
In case this feature already is implemented and I overlooked it, ofcourse let me know!
After an application has been uninstalled via BCU, the user is being asked if they want to get rid of leftover files like e.g. regkeys.
![bcu](https://user-images.githubusercontent.com/77630187/228594712-e407e2da-5bad-4c84-a5bd-faf155c51f8a.png)

I would love to have this feature seperately so the user can scan the system for leftover files that remain from uninstalls that have not been done via BCU.

**Comment by Klocman** [comment] 2023-03-30 20:26
There are some clean up tools in the Tools menu, but nothing exactly like you're asking. It's a potentially pretty useful feature but it's going to be difficult to avoid false positives and such I bet.

**Comment by Klocman** [comment] 2023-03-30 20:37
Duplicate of #476

**Closed by Klocman** 2023-03-30 20:37 UTC
Labels: enhancement
