### ISSUE TITLE
Kaspersky detected an attempt to access a malicious link

### ISSUE THREAD

**Issue by Chronosishere** [Klocman/Bulk-Crap-Uninstaller#524] opened 2023-07-20 21:58 UTC
Event: Access denied
User: ************
User type: Active user
Application name: BCUninstaller.exe
Application path: C:\Program Files\BCUninstaller\win-x64
Component: Web Anti-Virus
Result description: Blocked
Type: Malicious link
Name: http://bugsklocman.ddns.net:7721/GetAverageRatingsComp
Precision: Exactly
Threat level: High
Object type: Web page
Object name: GetAverageRatingsComp
Object path: http://bugsklocman.ddns.net:7721
Reason: Cloud Protection

It detected the attempt right at the startup of the application.

**Comment by Klocman** [comment] 2023-07-20 22:23
Duplicate of #519
False detection, no actions planned on my side.

**Closed by Klocman** 2023-07-20 22:23 UTC

**Comment by ArandomHitman** [comment] 2023-07-22 18:41
@Chronosishere You should consider getting the link whitelisted for Kaspersky to make sure this doesn't happen again and to make sure kaspersky doesn't flag BCuninstaller as malicious and delete key files.
