### ISSUE TITLE
[Feature Request] Windows Explorer Shell Extension Menu To Brute-Force Uninstall Stubborn Programs By Right-Clicking On Their Install Folder

### ISSUE THREAD

**Issue by MadZiontist** [Klocman/Bulk-Crap-Uninstaller#385] opened 2022-06-19 04:53 UTC
I really do like the app a good deal. It just doesn't remove nearly as many leftovers as Revo Uninstaller does, and I find myself going back to Revo, as it does a better job overall in getting as much garbage removed as possible. But I would love to be able to fully ditch Revo and move over to BCU.

Also, a feature in the Windows Explorer context menu to brute-force uninstall a folder for a program that won't otherwise uninstall would be great. Revo has this feature for the professional version.

**Comment by Klocman** [comment] 2022-06-20 05:16
Duplicate of #331
Implementation in progress here #372 

You can force uninstall a folder with the target tool, unless you're asking for something else, in which case please make a separate issue for it.

**Closed by Klocman** 2022-06-20 05:16 UTC
