### ISSUE TITLE
Dark Theme Mode

### ISSUE THREAD

**Issue by HitagiSenjougaharaFFXIV** [Klocman/Bulk-Crap-Uninstaller#437] opened 2022-12-27 18:32 UTC
Hello, i love this program but please allow us to have a dark mode. The launching page WHITE is burning my eyes @ night,,,, Thank you

**Comment by pizofreude** [comment] 2023-01-04 08:51
I second this motion.

**Comment by LewisJohnson** [comment] 2023-01-05 20:35
I've started work on this

**Comment by Klocman** [comment] 2023-01-06 07:20
Duplicate of #228

**Closed by Klocman** 2023-01-06 07:20 UTC

**Comment by Adil-Lidan** [comment] 2024-10-19 08:54
> I've started work on this

any hope ? :)
