### ISSUE TITLE
Cant uninstall System-Packages like: "Microsoft.BioEnrollment_cw5n1h2txyewy" and similar stuff

### ISSUE THREAD

**Issue by CodingMadness** [Klocman/Bulk-Crap-Uninstaller#601] opened 2024-04-17 15:16 UTC
Even if it is said to be removable, quiet or loud UN-installation always fails with error code: 1627, what does that mean, is it impossible to get rid of this crap now?

**Comment by Klocman** [comment] 2024-05-10 13:59
Duplicate of #181

**Closed by Klocman** 2024-05-10 13:59 UTC
