### ISSUE TITLE
Bug with  Sandboxie

### ISSUE THREAD

**Issue by mikhoul** [Klocman/Bulk-Crap-Uninstaller#164] opened 2018-01-10 05:16 UTC
BCU report 13.21 GB for the installation which is obviously not the case.

Screenshot: https://i.imgur.com/iSKPssJ.png

It seem that BCU take the whole "C:\Windows\Installer" folder size where "SandboxieInstall64.exe"
 reside with hundred of other MSI files and installation folders.

Screenshot 2: https://i.imgur.com/ulbAaTY.png

Regards :octocat:

**Comment by Klocman** [comment] 2018-01-10 05:58
Hello!

Can you select Sandboxie, go to menu > File > Export, and send me the .xml file? I'm guessing that the install location is incorrect for some reason.

**Comment by mikhoul** [comment] 2018-01-10 16:51
```
<?xml version="1.0"?>
<ApplicationEntrySerializer xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Items>
    <ApplicationUninstallerEntry>
      <DisplayName>Sandboxie 5.20 (64-bit)</DisplayName>
      <BundleProviderKey>00000000-0000-0000-0000-000000000000</BundleProviderKey>
      <DisplayIcon>K:\Sandboxie\Start.exe</DisplayIcon>
      <DisplayVersion>5.20</DisplayVersion>
      <EstimatedSize>13852320</EstimatedSize>
      <InstallDate>2012-01-10T12:10:43.9553822-05:00</InstallDate>
      <InstallLocation>C:\Windows\Installer</InstallLocation>
      <Is64Bit>X64</Is64Bit>
      <IsProtected>false</IsProtected>
      <IsRegistered>true</IsRegistered>
      <IsOrphaned>false</IsOrphaned>
      <IsUpdate>false</IsUpdate>
      <IsValid>true</IsValid>
      <Publisher>Sandboxie Holdings, LLC</Publisher>
      <QuietUninstallString>"K:\BCUninstaller\UninstallerAutomatizer.exe" Nsis /K "C:\Windows\Installer\SandboxieInstall64.exe" /remove</QuietUninstallString>
      <RatingId>Sandboxie</RatingId>
      <RegistryKeyName>Sandboxie</RegistryKeyName>
      <RegistryPath>HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Sandboxie</RegistryPath>
      <SystemComponent>false</SystemComponent>
      <UninstallerFullFilename>C:\Windows\Installer\SandboxieInstall64.exe</UninstallerFullFilename>
      <UninstallerKind>Nsis</UninstallerKind>
      <UninstallerLocation>C:\Windows\Installer</UninstallerLocation>
      <UninstallString>"C:\Windows\Installer\SandboxieInstall64.exe" /remove</UninstallString>
    </ApplicationUninstallerEntry>
  </Items>
</ApplicationEntrySerializer>
```

**Comment by Klocman** [comment] 2018-01-10 17:08
Yeah, as I expected the install location is wrong. Since it's most likely set incorrectly by Sandboxie installer, BCU is working as designed.

I saw other versions of this issue, e.g. some app was set install location to "C:\Windows". I'll think about how to tackle this issue.

**Comment by Klocman** [comment] 2018-02-18 12:45
This issue should be fixed for most cases now.

**Closed** 2018-02-18 12:44 UTC
Labels: bug
