### ISSUE TITLE
BitDefender flags BCUninstaller

### ISSUE THREAD

**Issue by NekoJonez** [Klocman/Bulk-Crap-Uninstaller#529] opened 2023-07-26 09:44 UTC
![image](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/4569581/277c990f-5bb9-4ac5-a2af-a72585570644)
This happened during the booting of the program.

**Comment by Klocman** [comment] 2023-07-26 14:12
Duplicate of #519

**Closed by Klocman** 2023-07-26 14:12 UTC
