### ISSUE TITLE
Feature suggestion:  Tracking installer changes

### ISSUE THREAD

**Issue by NicolasIceberg** [Klocman/Bulk-Crap-Uninstaller#342] opened 2022-02-02 16:50 UTC
First of all - thank you for a wonderful program. It does really well at uninstalling things. Great job!

But there is a feature that seems missing (for me, personally) that I think will be really cool. What if you could launch the program through Bull Crap Uninstaller and then track what files, folders, and registry entries the installer changed/created? You could then save file and registry system changes into a file and use it as a hint for the uninstaller later when you need to remove the program. 

Although helping a lot, BCU often leaves things anyway, and I get why - sometimes there can be no way to know whether or not the given folder came from the particular program. But with this feature, the task becomes trivial - just load a file with changes from the uninstaller (or from any other tracked program, for that matter) and it's done.

I have seen similar programs (like RegOrganizer or Uninstall Tool) implement this feature, as an example.

Let me know what you think!

**Comment by Klocman** [comment] 2022-02-06 15:01
Duplicate of https://github.com/Klocman/Bulk-Crap-Uninstaller/issues/258
Unfortunately the status didn't change, since I don't have much time to spend on the project anymore.

**Closed by Klocman** 2022-02-06 15:01 UTC
