### ISSUE TITLE
UniversalUninstaller constantly crashes

### ISSUE THREAD

**Issue by Express93** [Klocman/Bulk-Crap-Uninstaller#139] opened 2017-11-12 16:31 UTC
When I try to remove an unregistered application I continually get a popup saying UniversalUninstaller has stopped responding, it repeats about 3-4 times then flashes the "Searching for leftovers" window up momentarily, but just goes straight back to the list of applications.

**Comment by Klocman** [comment] 2017-11-12 20:27
Are you using the newest BCU version? If you can find it, send me the UniversalUninstaller's crash .dmp file.

**Comment by Express93** [comment] 2017-11-12 20:32
I am using the latest version... that specifically being whatever the auto-updater put me to: 3.19.0.32948

Where should I be looking to find the .dmp file?

**Comment by Klocman** [comment] 2017-11-13 05:39
Look in BCU's directory and in WER folders (search for folders named "WER", inside they have Queue and Archive folders). Usually they are located in C:\ProgramData\Microsoft\Windows\WER and C:\Users\%username%\AppData\Local\Microsoft\Windows

**Comment by Express93** [comment] 2017-11-14 07:49
Sorry but I can't find the .dmp files. I did however recently use disk clean up and I am not sure if it was before or after the errors.

It happens every time though so I will try get it to happen again and then take another look.

**Comment by Klocman** [comment] 2017-11-14 16:26
When the "stopped responding" dialog pops up make sure it finishes (don't close it and click check for solutions/etc. when asked). The .dmp file might not appear until then.

**Comment by Express93** [comment] 2017-11-19 21:33
I don't get the .dmp files and it doesn't even give me the choice of checking for a solution. I do have a couple .wer files if they're any use?

**Comment by Klocman** [comment] 2017-11-20 05:13
They could be useful, can you send them to me?

**Comment by bionoid** [comment] 2017-11-26 12:54
I am experiencing the same or a similar problem on win7pro 64bit; UniversalUninstaller 3.20.0.42878 crashes during uninstall, no option for report or anything else. It proceeds to the "look for leftovers", after which generally BCU exits (sometimes it does return successfully to the application list).

I can't find any .dmp files in the folders you mention. BCUininstaller.log only contains "application startup" entries, while StoreAppHelper.log contains the following repeated:

``
--- 26/11/2017 12:33:20
System.TypeLoadException: Could not find Windows Runtime type 'Windows.Management.Deployment.PackageManager'. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
   at StoreAppHelper.AppManager.<QueryApps>d__1.MoveNext()
   at StoreAppHelper.Program.Main(String[] args)
``

[Link to WER ReportQueue files](https://drive.google.com/drive/folders/1lOsNo4IKVECrG4IKaK9aekMuW8o1Bqnq?usp=sharing)

> You might have to run UniversalUninstaller manually for that to work (drag any unnecessary directory over it).

Dropping files on UniversalUninstaller flashes a dialog that I can't read, but nothing happens (dropped file/directory remains on disk). Running from CLI `C:\Program Files\BCUninstaller>UniversalUninstaller.exe "c:\temp\etc"` flashes the dialog and returns immediately; the directory is not touched. Running with /q also returns immediately, but it is deleted.

**Comment by Klocman** [comment] 2017-11-26 16:06
Can you check if this version works? To get extra information start it from a command prompt (has to be started as admin).
[UniversalUninstaller_Debug.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/1504032/UniversalUninstaller_Debug.zip)

**Comment by bionoid** [comment] 2017-11-26 16:37
Uploaded `uudebug.zip` to the previous google drive link  - it does not remove an empty directory:

``
C:\temp\uniuni>mkdir ..\test

C:\temp\uniuni>UniversalUninstaller.exe ..\test

C:\temp\uniuni>dir ..\test
 Volume in drive C has no label.
 Volume Serial Number is DEF6-B3AA

 Directory of C:\temp\test

26/11/2017  17:32    <DIR>          .
26/11/2017  17:32    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  23,328,219,136 bytes free
``

**Comment by Klocman** [comment] 2017-11-26 17:18
The dump file was a great help this version should work fine now: 
[UniversalUninstaller_Debug2.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/1504076/UniversalUninstaller_Debug2.zip)

**Comment by bionoid** [comment] 2017-11-26 19:07
Confirmed! At least it removes the directory when running from CLI :) I have not tested from bcuninstall, the naive approach of overwriting distribution files gives me FileLoadException. 

If there is anything more I can supply/test let me know, otherwise I will just wait for the next release, no rush here. Thank you for the excellent product & quick support!

**Comment by Klocman** [comment] 2017-11-26 20:30
Yeah, overwriting old version won't work because of different versions of shared .DLLs. You would have to compile entire BCU from source to have everything linked properly.

Thank you for the help. It looks like the issue is solved, so there's nothing left to do. I already released this week's version, so unfortunately you'll have to wait until next week though :(

**Closed by Klocman** 2017-11-26 20:30 UTC
