### ISSUE TITLE
Monitoring installations

### ISSUE THREAD

**Issue by harryray33** [Klocman/Bulk-Crap-Uninstaller#457] opened 2023-03-05 01:24 UTC
Is it possible to add an option to monitor a new installation that monitors everything that's installed, including reg entries?

It appears that programmes install hidden entries that aren't seen by uninstallers.
Thanks.

**Comment by Klocman** [comment] 2023-03-06 06:54
Duplicate of https://github.com/Klocman/Bulk-Crap-Uninstaller/issues/258, I'm currently not planning to add this feature because of limited time.

**Closed by Klocman** 2023-03-06 06:54 UTC
