### ISSUE TITLE
If no DarkMode maybe Themes

### ISSUE THREAD

**Issue by katastrophe92** [Klocman/Bulk-Crap-Uninstaller#452] opened 2023-02-26 09:17 UTC
First of all thank you for this amazing piece of software, I really LOVE IT. Any new news about a DarkMode since January 2019? I do not know hou hard it is to do it but maybe someone can help you to do it. Or a way to apply a Theme or to make one yourself. IDK if this is doable or not but. Thanks☺

**Comment by Klocman** [comment] 2023-03-03 18:13
At the moment I'm not planning to work on it. Some people have posted some progress in #228 so I suggest asking there.
Closing as duplicate of #228

**Closed by Klocman** 2023-03-03 18:13 UTC
