### ISSUE TITLE
Crash during load, program unusable (Uncaught exception in ListRefreshThread)

### ISSUE THREAD

**Issue by zulc22** [Klocman/Bulk-Crap-Uninstaller#324] opened 2021-10-19 20:00 UTC
![image](https://user-images.githubusercontent.com/54846511/137981838-5c53f9ca-7c6e-4fd8-8be1-62535c3bd8a5.png)

![image](https://user-images.githubusercontent.com/54846511/137981868-035fccef-c1ec-4fd4-ac50-b6ad370d8b7f.png)

**Comment by zulc22** [comment] 2021-11-12 18:32
reopening issue because i realized 102464 isn't the author and thus a fix has not been properly released yet

**Comment by Klocman** [comment] 2021-12-09 13:56
> reopening issue because i realized 102464 isn't the author and thus a fix has not been properly released yet

The fix is now merged, it will be included in the next release. If it fixes your issue then you can close this issue now.

**Comment by 102464** [comment] 2022-01-01 09:36
This bug-fixed version is compiled by myself: https://mega.nz/file/LaR0xBAT#mPDeEFvjSJ_-0i8xiZd-4bZcsgFdJWi8SQFBT4Jw5NQ
Please try it and let me know if the problem is solved or not.

**Comment by Klocman** [comment] 2022-02-07 17:43
It should be fixed in v5.2

**Comment by 102464** [comment] 2022-02-15 14:18
This bug fix has been added in 5.2 release: https://github.com/Klocman/Bulk-Crap-Uninstaller/releases/tag/v5.2
Confirmed it worked for me. Please close this issue if it works for you.

**Comment by Klocman** [comment] 2022-05-09 02:48
This should be fixed in the release coming out later today, so I'm closing the issue.

@FlavourWiener Looks like your bug report got lost if you sent it because of too aggressive filtering. If your issue persists after updating to the upcoming release, please create a new issue and send the bug report again.

**Closed by Klocman** 2022-05-09 02:48 UTC
Labels: bug
