### ISSUE TITLE
Chocolatey Package Scanning takes long time

### ISSUE THREAD

**Issue by chill1ne** [Klocman/Bulk-Crap-Uninstaller#253] opened 2020-03-05 06:57 UTC
WIN 1909
Latest Chocolatey

Tested Reinstall of application not working. 

My list of chocolatey apps is only around 15.

**Comment by Klocman** [comment] 2020-03-05 13:52
Duplicate of #248 

Before a fix is available you can turn off chocolatey scan in settings.

**Closed by Klocman** 2020-03-05 13:52 UTC
