### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by shafayetejaman** [Klocman/Bulk-Crap-Uninstaller#539] opened 2023-09-29 07:41 UTC
I've been using this app for quite some time now, and I'm finding the bright background a bit too harsh on my eyes, especially when I'm working late into the night. 

Would it be possible to request a feature for a dark theme? I think it would be really helpful for people like me who work long hours and need a more soothing interface.

**Comment by Klocman** [comment] 2023-09-29 07:44
Duplicate of #228

**Closed by Klocman** 2023-09-29 07:44 UTC
