### ISSUE TITLE
Real-Time installation monitor

### ISSUE THREAD

**Issue by PotoTan** [Klocman/Bulk-Crap-Uninstaller#264] opened 2020-05-30 15:29 UTC
monitoring program installs in real-time and when the program is no longer needed the system changes made by the installation of the monitored program could be fully reverted as if the program has never been installed before.

If the monitoring installation can bring a better uninstall effect, I hope you can develop it. 
Please think and judge independently whether it is necessary to develop this function to make Bulk-Crap-Uninstaller more perfect.

>The best way to make sure nothing gets missed after removing an application is to monitor and track the file and registry changes when you install the software so when it comes to removal, you have the chance to delete anything the original installer left behind

**Comment by Klocman** [comment] 2021-05-06 04:32
Duplicate of #258, I'm currently not planning to add this feature because of limited time.

**Closed by Klocman** 2021-05-06 04:32 UTC
